#!/bin/bash
# Setup E2E Test Environment
# Enables optional E2E test modes and configurations

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎭 Playwright E2E Test Configuration Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Create or update .env.e2e file
ENV_FILE=".env.e2e"

echo -e "${CYAN}📝 Setting up E2E test environment variables...${NC}"
echo ""

# CDN Failover Mode
echo -ne "${BLUE}Enable CDN failover tests? (y/n) [y]: ${NC}"
read -t 5 cdn_failover || cdn_failover="y"
echo ""

if [[ "$cdn_failover" =~ ^[Yy]$ ]]; then
    export E2E_CDN_FAILOVER_MODE="true"
    echo -e "${GREEN}✓ E2E_CDN_FAILOVER_MODE=true${NC}"
else
    export E2E_CDN_FAILOVER_MODE="false"
    echo -e "${YELLOW}✗ E2E_CDN_FAILOVER_MODE=false (skipped)${NC}"
fi
echo ""

# Search Failover Mode
echo -ne "${BLUE}Enable search failover tests? (y/n) [y]: ${NC}"
read -t 5 search_failover || search_failover="y"
echo ""

if [[ "$search_failover" =~ ^[Yy]$ ]]; then
    export E2E_FAILOVER_MODE="true"
    echo -e "${GREEN}✓ E2E_FAILOVER_MODE=true${NC}"
else
    export E2E_FAILOVER_MODE="false"
    echo -e "${YELLOW}✗ E2E_FAILOVER_MODE=false (skipped)${NC}"
fi
echo ""

# Stripe Test Mode
echo -ne "${BLUE}Enable Stripe subscription tests? (y/n) [y]: ${NC}"
read -t 5 stripe_mode || stripe_mode="y"
echo ""

if [[ "$stripe_mode" =~ ^[Yy]$ ]]; then
    export E2E_STRIPE_TEST_MODE="true"
    echo -e "${GREEN}✓ E2E_STRIPE_TEST_MODE=true${NC}"
else
    export E2E_STRIPE_TEST_MODE="false"
    echo -e "${YELLOW}✗ E2E_STRIPE_TEST_MODE=false (skipped)${NC}"
fi
echo ""

# Write environment variables to file
{
    echo "# E2E Test Configuration - Generated by setup-e2e-tests.sh"
    echo "# Run with: source .env.e2e before running tests"
    echo ""
    echo "# CDN Failover Tests - Tests CDN failure handling and fallback to origin"
    echo "E2E_CDN_FAILOVER_MODE=$E2E_CDN_FAILOVER_MODE"
    echo ""
    echo "# Search Failover Tests - Tests search service failover behavior"
    echo "E2E_FAILOVER_MODE=$E2E_FAILOVER_MODE"
    echo ""
    echo "# Stripe Subscription Tests - Tests payment processing and subscriptions"
    echo "E2E_STRIPE_TEST_MODE=$E2E_STRIPE_TEST_MODE"
    echo ""
    echo "# Additional E2E Configurations"
    echo "# E2E_DEBUG=false          # Enable verbose logging"
    echo "# E2E_SLOW_MO=0            # Slow down operations (ms)"
    echo "# PLAYWRIGHT_TIMEOUT=30000 # Test timeout in milliseconds"
} > "$ENV_FILE"

echo -e "${GREEN}✓ Configuration written to ${ENV_FILE}${NC}"
echo ""

# Display summary
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${CYAN}📋 Test Modes Summary${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "CDN Failover Mode:        ${E2E_CDN_FAILOVER_MODE}"
echo "  • Tests ~7 additional tests for CDN failure scenarios"
echo "  • Validates static asset fallback and video playback"
echo ""
echo "Search Failover Mode:     ${E2E_FAILOVER_MODE}"
echo "  • Tests search service failover behavior"
echo "  • Validates search continues during outages"
echo ""
echo "Stripe Test Mode:         ${E2E_STRIPE_TEST_MODE}"
echo "  • Tests subscription checkout and management"
echo "  • Uses Stripe test cards and sandbox mode"
echo ""

# Show how to use
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${CYAN}🚀 Next Steps${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Load the configuration:"
echo -e "   ${BLUE}source .env.e2e${NC}"
echo ""
echo "2. Run tests with these configurations:"
echo -e "   ${BLUE}npm run test:e2e${NC}"
echo -e "   or"
echo -e "   ${BLUE}bash run-playwright-tests.sh${NC}"
echo ""
echo "3. Or run with Makefile:"
echo -e "   ${BLUE}make test-frontend-e2e${NC}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Export and run tests if user wants
echo -ne "${BLUE}Run tests now with these settings? (y/n) [n]: ${NC}"
read -t 5 run_tests || run_tests="n"
echo ""

if [[ "$run_tests" =~ ^[Yy]$ ]]; then
    echo -e "${CYAN}Loading environment and running tests...${NC}"
    source "$ENV_FILE"
    npm run test:e2e
else
    echo -e "${YELLOW}Configuration saved. Load it with: ${BLUE}source .env.e2e${NC}"
fi
