#!/bin/bash
# Quick frontend test commands reference

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Frontend Test Commands Quick Reference"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚡ UNIT TESTS (VITEST)"
echo "  npm run test              # Interactive mode"
echo "  npm run test -- --run     # Run once and exit"
echo "  npm run test:ui           # Open UI dashboard"
echo "  npm run test:coverage     # Generate coverage report"
echo ""
echo "🌐 E2E TESTS (PLAYWRIGHT)"
echo "  npm run test:e2e          # Run all E2E tests"
echo "  npm run test:e2e:ui       # Open Playwright UI"
echo "  bash run-playwright-tests.sh # Verbose with checks"
echo ""
echo "📋 VIA MAKEFILE"
echo "  make test-frontend        # Unit tests (verbose)"
echo "  make test-frontend-e2e    # E2E tests with backend check"
echo "  make test-frontend-all    # Both unit and E2E"
echo ""
echo "📊 REPORTS"
echo "  npx playwright show-report # View last E2E test report"
echo "  open playwright-report/   # Direct access to report"
echo ""
echo "🔧 REQUIREMENTS FOR E2E"
echo "  ✓ Backend running on http://localhost:8080"
echo "  ✓ Database seeded with test data"
echo "  ✓ Playwright browsers installed (npx playwright install)"
echo ""
echo "⚙️  CONFIGURATION"
echo "  playwright.config.ts      # Playwright settings (baseURL, timeout, etc.)"
echo "  vitest.config.ts          # Vitest settings"
echo "  e2e/                      # All E2E test files"
echo "  src/                      # Unit test files (*.test.tsx)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
