linters-settings:
  dupl:
    threshold: 200  # Increased to reduce false positives
  goconst:
    min-len: 3
    min-occurrences: 8  # Increased to reduce noise
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - paramTypeCombine
      - emptyStringTest
      - rangeValCopy
      - sprintfQuotedString
      - emptyFallthrough
      - unnamedResult
      - hugeParam
      - ifElseChain
      - unnecessaryBlock
      - httpNoBody
      - exitAfterDefer
      - deferInLoop
      - builtinShadowDecl
  gocyclo:
    min-complexity: 45  # Increased from 25 to allow complex functions
  govet:
    disable:
      - shadow  # Temporarily disable shadow variable checks

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - staticcheck
    # Temporarily disabled - creates too much noise
    # - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - goconst
    - path: _test\.go
      linters:
        - govet
      text: "shadow: "
    - path: config/config\.go
      linters:
        - goconst
    # Ignore ineffassign in specific file with known false positive
    - path: internal/repository/audit_log_repository\.go
      linters:
        - ineffassign

run:
  timeout: 5m
