#!/bin/bash
# Quick test commands reference

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Backend Test Commands Quick Reference"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📦 SETUP ENVIRONMENT"
echo "  ./setup-test-env.sh"
echo "  └─ Generates MFA keys, Stripe secrets, JWT tokens, etc."
echo ""
echo "🧪 RUN ALL TESTS (RECOMMENDED)"
echo "  INTEGRATION=1 E2E=1 ./run-tests-verbose.sh"
echo "  └─ Auto-setup + all 36 test packages + verbose output"
echo ""
echo "⚡ UNIT TESTS ONLY"
echo "  ./run-tests-verbose.sh"
echo "  └─ Fast tests, no Docker containers needed"
echo ""
echo "🔗 INTEGRATION TESTS"
echo "  INTEGRATION=1 ./run-tests-verbose.sh"
echo "  └─ Requires: make test-setup (starts Docker containers)"
echo ""
echo "🌐 E2E TESTS"
echo "  E2E=1 ./run-tests-verbose.sh"
echo "  └─ Requires: make test-setup + test data seeding"
echo ""
echo "🚫 SKIP AUTO-SETUP (use existing .env.test)"
echo "  SETUP_ENV=0 INTEGRATION=1 E2E=1 ./run-tests-verbose.sh"
echo ""
echo "📋 VIA MAKEFILE (RECOMMENDED)"
echo "  make test-help               # Show this help"
echo "  make test                    # Unit tests (verbose)"
echo "  make test INTEGRATION=1      # + Integration tests (verbose)"
echo "  make test INTEGRATION=1 E2E=1 # All tests (verbose)"
echo "  make test-unit               # Fast unit tests only"
echo "  make test-integration        # Integration tests only"
echo ""
echo "🐳 DOCKER MANAGEMENT"
echo "  make test-setup     # Start test containers"
echo "  make test-teardown  # Stop test containers"
echo ""
echo "📄 GENERATED FILES"
echo "  .env.test          # Test environment config (regenerate anytime)"
echo "  test-output.log    # Last test run output"
echo ""
echo "📚 DOCUMENTATION"
echo "  TEST_SETUP_GUIDE.md    # Complete setup guide"
echo "  TEST_SETUP_SUMMARY.md  # What we created and why"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
