import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function KarmaBreakdownChart({ breakdown }) {
    const total = breakdown.total_karma;
    const clipPercentage = total > 0 ? (breakdown.clip_karma / total) * 100 : 0;
    const commentPercentage = total > 0 ? (breakdown.comment_karma / total) * 100 : 0;
    return (_jsxs("div", { className: "p-6 bg-gray-800 rounded-lg", children: [_jsx("h3", { className: "mb-4 text-lg font-semibold text-white", children: "Karma Breakdown" }), _jsx("div", { className: "mb-6", children: _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-4xl font-bold text-purple-400", children: total.toLocaleString() }), _jsx("div", { className: "mt-1 text-sm text-gray-400", children: "Total Karma" })] }) }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex justify-between mb-1 text-sm", children: [_jsx("span", { className: "text-gray-300", children: "\uD83D\uDCF9 Clip Karma" }), _jsx("span", { className: "font-semibold text-purple-400", children: breakdown.clip_karma.toLocaleString() })] }), _jsx("div", { className: "w-full h-2 bg-gray-700 rounded-full", children: _jsx("div", { className: "h-2 transition-all duration-300 bg-purple-500 rounded-full", style: { width: `${clipPercentage}%` } }) })] }), _jsxs("div", { children: [_jsxs("div", { className: "flex justify-between mb-1 text-sm", children: [_jsx("span", { className: "text-gray-300", children: "\uD83D\uDCAC Comment Karma" }), _jsx("span", { className: "font-semibold text-blue-400", children: breakdown.comment_karma.toLocaleString() })] }), _jsx("div", { className: "w-full h-2 bg-gray-700 rounded-full", children: _jsx("div", { className: "h-2 transition-all duration-300 bg-blue-500 rounded-full", style: { width: `${commentPercentage}%` } }) })] })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4 pt-4 mt-6 border-t border-gray-700", children: [_jsxs("div", { className: "text-center", children: [_jsxs("div", { className: "text-2xl font-bold text-purple-400", children: [clipPercentage.toFixed(1), "%"] }), _jsx("div", { className: "text-xs text-gray-400", children: "from clips" })] }), _jsxs("div", { className: "text-center", children: [_jsxs("div", { className: "text-2xl font-bold text-blue-400", children: [commentPercentage.toFixed(1), "%"] }), _jsx("div", { className: "text-xs text-gray-400", children: "from comments" })] })] })] }));
}
export function KarmaStats({ breakdown }) {
    return (_jsxs("div", { className: "grid grid-cols-3 gap-4", children: [_jsxs("div", { className: "p-4 text-center bg-gray-800 rounded-lg", children: [_jsx("div", { className: "text-2xl font-bold text-purple-400", children: breakdown.total_karma.toLocaleString() }), _jsx("div", { className: "mt-1 text-sm text-gray-400", children: "Total" })] }), _jsxs("div", { className: "p-4 text-center bg-gray-800 rounded-lg", children: [_jsx("div", { className: "text-2xl font-bold text-purple-400", children: breakdown.clip_karma.toLocaleString() }), _jsx("div", { className: "mt-1 text-sm text-gray-400", children: "Clips" })] }), _jsxs("div", { className: "p-4 text-center bg-gray-800 rounded-lg", children: [_jsx("div", { className: "text-2xl font-bold text-blue-400", children: breakdown.comment_karma.toLocaleString() }), _jsx("div", { className: "mt-1 text-sm text-gray-400", children: "Comments" })] })] }));
}
