#!/bin/bash
# Script to manually test Sentry integration in development

echo "==================================="
echo "Sentry Integration Testing Guide"
echo "==================================="
echo ""
echo "This script provides instructions for manually testing the Sentry integration."
echo ""
echo "Prerequisites:"
echo "1. Create a Sentry account at https://sentry.io"
echo "2. Create a new React Native project in Sentry"
echo "3. Copy the DSN from your Sentry project settings"
echo ""
echo "Setup:"
echo "1. Copy .env.example to .env:"
echo "   cp .env.example .env"
echo ""
echo "2. Edit .env and add your Sentry credentials:"
echo "   EXPO_PUBLIC_SENTRY_DSN=https://your-key@sentry.io/your-project-id"
echo "   EXPO_PUBLIC_SENTRY_ENVIRONMENT=development"
echo "   EXPO_PUBLIC_SENTRY_ENABLED=true"
echo ""
echo "3. Start the app:"
echo "   npm start"
echo ""
echo "Testing Scenarios:"
echo ""
echo "1. Test JavaScript Error:"
echo "   - Add this code to any component:"
echo "   throw new Error('Test Sentry JS error');"
echo ""
echo "2. Test Error Boundary:"
echo "   - Create a component that throws during render:"
echo "   const BuggyComponent = () => { throw new Error('Test error boundary'); };"
echo ""
echo "3. Test Manual Error Capture:"
echo "   - Import and use captureException:"
echo "   import { captureException } from '@/lib/sentry';"
echo "   try { /* something */ } catch (e) { captureException(e); }"
echo ""
echo "4. Test User Context:"
echo "   - Log in with your account"
echo "   - Trigger an error"
echo "   - Check Sentry dashboard for user context (ID and username)"
echo ""
echo "5. Test Performance Monitoring:"
echo "   - Navigate between screens"
echo "   - Check Sentry Performance tab for transactions"
echo "   - Look for 'App Start' and 'Screen: *' transactions"
echo ""
echo "Verification:"
echo "1. Go to your Sentry project dashboard:"
echo "   https://sentry.io/organizations/<your-org>/projects/<your-project>/"
echo ""
echo "2. Check Issues tab for captured errors"
echo "3. Check Performance tab for transactions"
echo "4. Verify stack traces are symbolicated (readable)"
echo "5. Verify user context is attached to errors"
echo "6. Verify no PII (emails, phones) is captured"
echo ""
echo "For production builds:"
echo "1. Build with EAS: eas build --profile preview --platform all"
echo "2. Source maps will be automatically uploaded"
echo "3. Test crashes in the built app"
echo "4. Verify symbolication works in Sentry"
echo ""
echo "Documentation: See SENTRY_INTEGRATION.md for full details"
echo ""
