import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { Helmet } from 'react-helmet-async';
import { getUserStats } from '../lib/analytics-api';
import { MetricCard, PieChartComponent } from '../components/analytics';
import { format } from 'date-fns';
const PersonalStatsPage = () => {
    // Fetch user statistics
    const { data: stats, isLoading, error } = useQuery({
        queryKey: ['userStats'],
        queryFn: getUserStats,
    });
    if (error) {
        return (_jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8", children: _jsx("div", { className: "bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4", children: _jsx("p", { className: "text-red-800 dark:text-red-200", children: "Failed to load your statistics. Please try again later." }) }) }));
    }
    return (_jsxs(_Fragment, { children: [_jsx(Helmet, { children: _jsx("title", { children: "My Statistics - Clipper" }) }), _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8", children: [_jsxs("div", { className: "mb-8", children: [_jsx("h1", { className: "text-3xl font-bold text-gray-900 dark:text-white", children: "My Statistics" }), _jsx("p", { className: "mt-2 text-gray-600 dark:text-gray-400", children: "Your activity and engagement on the platform" })] }), isLoading ? (_jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8", children: [1, 2, 3, 4, 5, 6, 7, 8].map((i) => (_jsxs("div", { className: "bg-white dark:bg-gray-800 rounded-lg shadow p-6 animate-pulse", children: [_jsx("div", { className: "h-4 bg-gray-200 dark:bg-gray-700 rounded w-1/2 mb-4" }), _jsx("div", { className: "h-8 bg-gray-200 dark:bg-gray-700 rounded w-3/4" })] }, i))) })) : stats ? (_jsxs(_Fragment, { children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8", children: [_jsx(MetricCard, { title: "Clips Upvoted", value: stats.clips_upvoted, subtitle: "Positive engagement" }), _jsx(MetricCard, { title: "Clips Downvoted", value: stats.clips_downvoted, subtitle: "Negative feedback" }), _jsx(MetricCard, { title: "Comments Posted", value: stats.comments_posted, subtitle: "Your contributions" }), _jsx(MetricCard, { title: "Clips Favorited", value: stats.clips_favorited, subtitle: "Saved clips" }), _jsx(MetricCard, { title: "Searches Performed", value: stats.searches_performed, subtitle: "Exploration" }), _jsx(MetricCard, { title: "Days Active", value: stats.days_active, subtitle: "Platform engagement" }), _jsx(MetricCard, { title: "Karma Earned", value: stats.total_karma_earned, subtitle: "Reputation points" }), _jsx(MetricCard, { title: "Last Active", value: stats.last_active_at
                                            ? format(new Date(stats.last_active_at), 'MMM dd, yyyy')
                                            : 'N/A', subtitle: "Most recent activity" })] }), (stats.clips_upvoted > 0 || stats.clips_downvoted > 0) && (_jsxs("div", { className: "mb-8", children: [_jsx("h2", { className: "text-xl font-bold text-gray-900 dark:text-white mb-4", children: "Voting Behavior" }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-6", children: [_jsx(PieChartComponent, { data: [
                                                    { name: 'Upvotes', value: stats.clips_upvoted },
                                                    { name: 'Downvotes', value: stats.clips_downvoted },
                                                ], title: "Upvotes vs Downvotes", colors: ['#10b981', '#ef4444'] }), _jsxs("div", { className: "bg-white dark:bg-gray-800 rounded-lg shadow p-6", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 dark:text-white mb-4", children: "Engagement Summary" }), _jsxs("div", { className: "space-y-4", children: [_jsx("div", { children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-gray-600 dark:text-gray-400", children: "Total Votes Cast" }), _jsx("span", { className: "text-sm font-semibold text-gray-900 dark:text-white", children: stats.clips_upvoted + stats.clips_downvoted })] }) }), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsx("span", { className: "text-sm text-gray-600 dark:text-gray-400", children: "Positivity Rate" }), _jsxs("span", { className: "text-sm font-semibold text-gray-900 dark:text-white", children: [((stats.clips_upvoted /
                                                                                        Math.max(stats.clips_upvoted + stats.clips_downvoted, 1)) *
                                                                                        100).toFixed(1), "%"] })] }), _jsx("div", { className: "w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2", children: _jsx("div", { className: "bg-green-500 h-2 rounded-full", style: {
                                                                                width: `${(stats.clips_upvoted /
                                                                                    Math.max(stats.clips_upvoted + stats.clips_downvoted, 1)) *
                                                                                    100}%`,
                                                                            } }) })] }), _jsx("div", { children: _jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsx("span", { className: "text-sm text-gray-600 dark:text-gray-400", children: "Comments per Vote" }), _jsx("span", { className: "text-sm font-semibold text-gray-900 dark:text-white", children: (stats.comments_posted /
                                                                                Math.max(stats.clips_upvoted + stats.clips_downvoted, 1)).toFixed(2) })] }) })] })] })] })] })), _jsxs("div", { className: "bg-white dark:bg-gray-800 rounded-lg shadow p-6", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 dark:text-white mb-4", children: "Account Summary" }), _jsxs("dl", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs("div", { children: [_jsx("dt", { className: "text-sm font-medium text-gray-500 dark:text-gray-400", children: "Total Karma" }), _jsx("dd", { className: "mt-1 text-2xl font-semibold text-gray-900 dark:text-white", children: stats.total_karma_earned })] }), _jsxs("div", { children: [_jsx("dt", { className: "text-sm font-medium text-gray-500 dark:text-gray-400", children: "Days Active" }), _jsx("dd", { className: "mt-1 text-2xl font-semibold text-gray-900 dark:text-white", children: stats.days_active })] }), _jsxs("div", { children: [_jsx("dt", { className: "text-sm font-medium text-gray-500 dark:text-gray-400", children: "Contribution Score" }), _jsx("dd", { className: "mt-1 text-2xl font-semibold text-gray-900 dark:text-white", children: stats.comments_posted + stats.clips_upvoted })] }), _jsxs("div", { children: [_jsx("dt", { className: "text-sm font-medium text-gray-500 dark:text-gray-400", children: "Engagement Level" }), _jsx("dd", { className: "mt-1 text-2xl font-semibold text-gray-900 dark:text-white", children: stats.comments_posted > 50 || stats.clips_upvoted > 100
                                                            ? 'High'
                                                            : stats.comments_posted > 10 || stats.clips_upvoted > 20
                                                                ? 'Medium'
                                                                : 'Low' })] })] })] })] })) : null] })] }));
};
export default PersonalStatsPage;
